jobs:
    main:
        image: node:{{NODE_VERSION}}
        matrix:
            NODE_VERSION: [4,5,6]
        steps:
            - npm install
            - test: npm test
            - build: npm run build

    publish:
        image: node:4
        steps:
            - install: npm publish
